# Generated by Django 4.1.4 on 2022-12-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_model',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
