# Generated by Django 4.1.4 on 2022-12-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_ips_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ips_model',
            table='IP',
        ),
        migrations.AlterModelTable(
            name='project_model',
            table='Usuarios',
        ),
    ]
