# Generated by Django 4.1.4 on 2022-12-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_ips_model_table_alter_project_model_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project_model',
            table='Proyectos',
        ),
    ]
