# Generated by Django 4.1.4 on 2022-12-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_model_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_model',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
